server:
  port: 8774
management.security.enabled: false
spring:
  application:
    name: service-ops-zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/
  instance:
    preferIpAddress: true