version: '2'

networks:
  microservice-tier:
    driver: bridge
  ops-tier:
    driver: bridge

services:
  eureka-server1:
    image: service-hive/eureka-server1:1.0.1
    ports:
      - 8761:8761  
    networks:
      - microservice-tier
      - ops-tier
      
  eureka-server2:
    image: service-hive/eureka-server2:1.0.1
    ports:
      - 8762:8761
    networks:
      - microservice-tier
      - ops-tier
         
  admin-server:
    image: service-hive/admin-server:1.0.1
    ports:
      - 8771:8771
    networks:
      - microservice-tier
      - ops-tier
  
  hystrix-dashboard:
    image: service-hive/hystrix-dashboard:1.0.1
    ports:
      - 8772:8772
    networks:
      - microservice-tier
      - ops-tier
      
  zipkin-server:
    image: service-hive/zipkin-server:1.0.1
    ports:
      - 8774:8774
    networks:
      - microservice-tier
      - ops-tier
      
  api-gateway:
    image: service-hive/api-gateway:1.0.1
    ports:
      - 8443:8443
    networks:
      - microservice-tier
      
  demo-hr-service:
    image: service-hive/demo-hr-service:1.0.1
    ports:
      - 8080:8080
    networks:
      - microservice-tier
      
  demo-hr-client-with-feign-hystrix:
    image: service-hive/demo-hr-client-with-feign-hystrix:1.0.1
    ports:
      - 8083:8083
    networks:
      - microservice-tier

  demo-hr-client-with-ribbon-hystrix:
    image: service-hive/demo-hr-client-with-ribbon-hystrix:1.0.1
    ports:
      - 8082:8082
    networks:
      - microservice-tier