server:
  port: 8443
  ssl.enabled: true
  ssl.key-store: /servicehive.jks
  #ssl.key-store: ./docker/ssl-certs-build/servicehive.jks
  ssl.key-store-password: 123456
  ssl.key-store-type: PKCS12
  ssl.keyAlias: eureka-client
management:
  security.enabled: false
spring:
  application.name: service-hive-api-gateway
  sleuth:
    sampler.percentage: 0.5
  zipkin:
    baseUrl: http://zipkin-server:8774
    enabled: true
eureka:
  client:
    serviceUrl.defaultZone: https://eureka-server1:8761/eureka/,https://eureka-server2:8761/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
ribbon.filter.metadata.enabled: true
zuul:
  ignored-services: '*'
  routes:
    hr-service:
      path: /hr/**
      service-id: demo-hr-service
    hr-client:
      path: /client/**
      service-id: demo-hr-client
    hr-client-hystrix:
      path: /hystrix/**
      service-id: demo-hr-client-with-hystrix