spring:
  application:
    name: service-hive-api-gateway
server:
  port: 8443
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/
  instance:
    preferIpAddress: true
ribbon.filter.metadata.enabled: true
zuul:
  ignored-services: service-hive-eureka,service-ops-admin-server,service-ops-zipkin-server,service-ops-hystrix-dashboard
  routes:
    hr-service:
      path: /hr/**
      service-id: demo-hr-service
    hr-client:
      path: /client/**
      service-id: demo-hr-client
    hr-client-hystrix:
      path: /hystrix/**
      service-id: demo-hr-client-with-hystrix