spring:
  application:
    name: service-hive-api-gateway
server:
  port: 8443
eureka:
  client:
    serviceUrl:
      defaultZone: http://devcloud-eureka1:8761/eureka/,http://devcloud-eureka2:8762/eureka/
  instance:
    preferIpAddress: true
zuul:
  ignored-services: demo-consumer-feign
  routes:
    hr:
      path: /hr/**
      service-id: demo-service-provider
