spring:
  application:
    name: service-hive-eureka
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl:
      defaultZone: http://devcloud-eureka2:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl:
      defaultZone: http://devcloud-eureka1:8761/eureka/