spring:
  application.name: service-hive-eureka
  profiles.active: peer1
---
spring:
  profiles: peer1
server:
  port: 8761
  ssl.enabled: true
  ssl.key-store: /servicehive.jks
  ssl.key-store-password: 123456
  ssl.key-store-type: PKCS12
  ssl.keyAlias: eureka-server
management:
  security.enabled: false
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl.defaultZone: https://eureka-server2:8761/eureka/
---
spring:
  profiles: peer2
server:
  port: 8761
  ssl.enabled: true
  ssl.key-store: /servicehive.jks
  ssl.key-store-password: 123456
  ssl.key-store-type: PKCS12
  ssl.keyAlias: eureka-server
management:
  security.enabled: false
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl.defaultZone: https://eureka-server1:8761/eureka/