spring:
  application:
    name: service-hive-eureka
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 8761
  ssl.key-store: classpath:servicehive.keystore
  ssl.key-store-password: 123456
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: servicehive-ca
management.security.enabled: false
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl:
      defaultZone: https://eureka-server2:8761/eureka/
---
spring:
  profiles: peer2
server:
  port: 8761
  ssl.key-store: classpath:servicehive.keystore
  ssl.key-store-password: 123456
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: servicehive-ca
management.security.enabled: false
eureka:
  datacenter: huaweicloud
  environment: dev
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    region: cn-east-1
    serviceUrl:
      defaultZone: https://eureka-server1:8761/eureka/