server:
  port: 8081
  ssl.enabled: true
  ssl.key-store: /servicehive.jks
  ssl.key-store-password: 123456
  ssl.key-store-type: PKCS12
  ssl.keyAlias: eureka-client
management:
  security.enabled: false
spring:
  application.name: demo-hr-client
  profiles.active: prod
  sleuth:
    sampler.percentage: 0.5
  zipkin:
    baseUrl: http://zipkin-server:8774
    enabled: true
eureka:
  client:
    serviceUrl.defaultZone: https://eureka-server1:8761/eureka/,https://eureka-server2:8761/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
ribbon:
  eureka.enabled: true

---
spring:
  profiles: prod
eureka:
  instance:
    metadata-map:
      env: prod
---
spring:
  profiles: canary
eureka:
  instance:
    metadata-map:
      env: canary