server:
  port: 8773
management.security.enabled: false
security.basic.enabled: false
spring:
  application.name: service-ops-hystrix-turbine
turbine:
  appConfig: demo-hr-client-with-ribbon-hystrix,demo-hr-client-with-hystrix
  aggregator.clusterConfig: default
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server1:8761/eureka/,https://eureka-server2:8761/eureka/
  instance:
    preferIpAddress: true