version: '2'

networks:
  microservice-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  eureka-server1:
    image: service-hive/eureka-server:1.0.0
    ports:
      - 8761:8761  
    networks:
      - microservice-tier
      
  eureka-server2:
    image: service-hive/eureka-server:1.0.0
    ports:
      - 8762:8761
    networks:
      - microservice-tier
         
  admin-server:
    image: service-hive/admin-server:1.0.0
    ports:
      - 8771:8771
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier
  
  hystrix-dashboard:
    image: service-hive/hystrix-dashboard:1.0.0
    ports:
      - 8772:8772
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier
      
  zipkin-server:
    image: service-hive/zipkin-server:1.0.0
    ports:
      - 8774:8774
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier
      
  api-gateway:
    image: service-hive/api-gateway:1.0.0
    ports:
      - 8443:8443
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier
      
  demo-hr-service:
    image: service-hive/demo-hr-service:1.0.0
    ports:
      - 8080
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier
      
  demo-hr-client-with-ribbon-hystrix:
    image: service-hive/demo-hr-client-with-ribbon-hystrix:1.0.0
    ports:
      - 8082
    links:
      - eureka-server1
      - eureka-server2
    networks:
      - microservice-tier