spring:
  application.name: service-ops-admin-server
server:
  port: 8771
  ssl.enabled: true
  ssl.key-store: /servicehive.jks
  ssl.key-store-password: 123456
  ssl.key-store-type: PKCS12
  ssl.keyAlias: eureka-client
management:
  security.enabled: false
  health.sensitive: false
  health.enabled: true
eureka:
  client:
    serviceUrl.defaultZone: https://eureka-server1:8761/eureka/,https://eureka-server2:8761/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}