server:
  port: 8082
spring:
  application:
    name: demo-consumer-feign-with-hystrix-stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://devcloud-eureka1:8761/eureka/,http://devcloud-eureka2:8762/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true