server:
  port: 8081
management.security.enabled: false
spring:
  application:
    name: demo-hr-client
  sleuth:
    sampler:
      percentage: 0.5
  zipkin:
    baseUrl: http://zipkin-server:8774
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true